export const DEFINE_PROJECTS = 'DEFINE_PROJECTS'
export const CHANGE_PROJECT = 'CHANGE_PROJECT'
export const DELETE_PROJECT = 'DELETE_PROJECT'
export const ADD_PROJECT = 'ADD_PROJECT'

export const NOTIFICATION = 'NOTIFICATION'

export const DEFINE_TASKS = 'DEFINE_TASKS'
export const ADD_TASK = 'ADD_TASK'
export const UPDATE_TASK = 'UPDATE_TASK'
